import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pocket Relay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/logo.svg" alt="Logo" className={styles.logo} />

        <h1 className={styles.title}>
          Coming Soon <a href="https://github.com/PocketRelay">Pocket Relay</a>
        </h1>
      </main>
    </div>
  )
}
